#!/bin/bash
#Auf Knopfdruck kompiliert das Script C-Code und führt das Programm aus
#Sehr nützlich! Dieses Script in einem Fenster öffnen, vi mit dem Sourcecode in anderem Fenster.

if [ -e $1 ]
then
	rm -f ./a.out
	clear
else
	echo "$1 ist kein gültiger Dateiname"
	exit
fi

SAPIstEinBloedesFach=1
while [ $SAPIstEinBloedesFach -eq 1 ]
do
	clear
	rm -f ./a.out
	gcc $1
	echo "" #Leerzeile zwischen evtl. Kompilerwarnungen und Programmausführung
	./a.out
	echo -en "\033[1;30m\nProgramm beendet mit Exit Code $?. "
	read -p "Weiter? " auswahl #g oder nichts eingeben, weiter durch Drücken der Enter Taste
	echo -e "\033[0m"

	if [ $auswahl = "g" ]
	then
		clear
		rm -f ./a.out
		gcc -g $1
		echo ""
		gdb ./a.out
		echo ""
		read -p "Programm beendet" auswahl
	elif [ $auswahl = "q" ]
	then
		exit
	fi

done
